name = "SingleFieldStructArrays"
uuid = "5dd5ea32-d67d-426d-b4ce-2ad113187929"
authors = ["Ingraham, Daniel James (GRC-LTV0) <daniel.j.ingraham@nasa.gov>"]
version = "0.3.1"

[compat]
julia = "1.8.5"
